### ISSUE TITLE
Lua Error "unrecognized line: SELECT"

### ISSUE THREAD

**Issue by krzychu135** [jzwinck/redis-wireshark#5]
Lua plugin from last commit (a6236b2773d9f07a2ae7589114f1db07860af17f) shows error like this:

Redis Multi-Bulk Reply Lua Error: [string "/home/krzysiek/.config/wireshark/plugins/redis-wireshark.lua"]:38: unrecognized line: SELECT     [Expert Info (Error/Undecoded): Lua Error: [string "/home/krzysiek/.config/wireshark/plugins/redis-wireshark.lua"]:38: unrecognized line: SELECT]         [Lua Error: [string "/home/krzysiek/.config/wireshark/plugins/redis-wireshark.lua"]:38: unrecognized line: SELECT]

Previous version i used (23842e5a9dc891782466f7a1eee5f303482edc52) works good.
Redis Multi-Bulk Reply
    Redis Bulk Reply
        Value: SELECT
    Redis Bulk Reply
        Value: 10

**Comment by jzwinck** [comment]
@krzychu135 Thanks for the report.  Please consider submitting a pull request with a fix.

@johnzeng If you have any ideas on how to fix this, a PR or explanation would be appreciated.

**Comment by johnzeng** [comment]
I have no idea about it @politician can you upload a sample so I can reproduce this error ?

**Comment by krzychu135** [comment]
@johnzeng working for me.
Thanks for quick fix

**Comment by jzwinck** [comment]
Fixed by #6.
